### ISSUE TITLE
Pomysły:

### ISSUE THREAD

**Issue by pawo97** [ericssondreamteam/OutlookPlugin#35]
- [x] Spróbować odpalić ostatnią działającą wersję na kompie Mateusza
- [x] Spróbować odpalić na komputerze Pawła
- [x] Spróbować odpalić na komputerze kolegi Karola
- [x] wykorzystać publikacje certyfikatu https://www.youtube.com/watch?time_continue=56&v=TPpSD-B5nb0
- [x] napisać do support w ostateczności

**Comment by Kar0lLasek** [comment]
Przy jednym aktywnym koncie działa prawidłowo.
